### ISSUE TITLE
Profile.MaxRate: problem with unmarshalling - incorrect type

### ISSUE THREAD

**Issue by jar3k** [Telestream/telestream-cloud-go-sdk#6]
Hey guys,

Unmarshaling `Profile` is failing because `Profile.MaxRate` is defined as a string (the Flip API returns an integer).

Could you change a type of [Profile.MaxRate](https://github.com/Telestream/telestream-cloud-go-sdk/blob/master/flip/profile.go#L166) from `string` to `int32` as it is in [ProfileBody.MaxRate](https://github.com/Telestream/telestream-cloud-go-sdk/blob/master/flip/profile_body.go#L129)?

Thanks in advance!

**Comment by gawor04** [comment]
Hello,
Problem fixed, Profile.MaxRate changed to int32, also Profile.BufferSize and ProfileBody.BufferSize changed to int32.

**Comment by jar3k** [comment]
Perfect, thanks a lot @gawor04 !
